services:
  # --- IMAGE 1 : LE SERVEUR DE JEU ---
  game-service:
    build: ./game-server
    container_name: cloud-game-engine
    restart: unless-stopped
    # Inversion : Le jeu attend l'API pour pouvoir lui envoyer son "Ping" au d√©marrage
    depends_on:
      - api-cloud
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    networks:
      - cloud-network

  # --- IMAGE 2 : L'API ---
  api-cloud:
    build: ./backend
    container_name: cloud-api
    environment:
      - API_ENV=production
      - GAME_SERVER_HOST=game-service
      - API_VERSION=1.0.0 
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - cloud-network

  # --- IMAGE 3 : L'INTERFACE WEB ---
  interface-web:
    build: ./frontend
    container_name: cloud-portal
    ports:
      - "8080:80" 
    volumes:
      - ./frontend/src:/var/www/my-cloud/html
    depends_on:
      - api-cloud
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
    networks:
      - cloud-network

networks:
  cloud-network:
    driver: bridge